version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pedrorey-firefly-iii_server_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: fireflyiii/core:latest
    # This image runs under the user/group www-data:www-data
    # user: "1000:1000"
    restart: on-failure
    environment:
      APP_KEY: $APP_FIREFLY_III_APP_KEY
      DB_HOST: firefly-iii_db_1
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: fireflyiii
      DB_USERNAME: fireflyiii
      DB_PASSWORD: psfinance*77
    volumes:
      - ${APP_DATA_DIR}/data/upload:/var/www/html/storage/upload
      - ${APP_DATA_DIR}/data/logs:/var/www/html/storage/logs
  
  db:
    image: mariadb:lts
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
       - 3306
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "fireflyiii"
      MYSQL_USER: "fireflyiii"
      MYSQL_PASSWORD: "psfinance*77"
      MYSQL_ROOT_PASSWORD: "psfinance*77"
