version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  importer:
    image: fireflyiii/data-importer:latest
    hostname: pedrorey-firefly-iii-importer_importer_1
    restart: on-failure
    container_name: pedrorey-firefly-iii-importer_importer_1
    ports:
      - '30010:8080'
    environment:
      FIREFLY_III_URL: http://pedrorey.local:30009
      VANITY_URL: http://pedrorey.local
      DB_HOST: pedrorey.local
      DB_PORT: 32772
      DB_CONNECTION: mysql
      DB_DATABASE: fireflyiii
      DB_USERNAME: fireflyiii
      DB_PASSWORD: psfinance*77
      MYSQL_DATABASE: fireflyiii
      MYSQL_USER: fireflyiii
      MYSQL_PASSWORD: psfinance*77
